### ISSUE TITLE
Index on label field in labels table

### ISSUE THREAD

**Issue by tomlee** [yam-ai/bert-multilabel-classifier#1]
Since `SELECT DISTINCT label FROM labels` is used in [`data.py`](https://github.com/yam-ai/bert-multilabel-classifier/blob/9e115fd4fe35c0c39e4c699792e2535c5c3965e3/data.py), it will be more efficient to create an index for `label` in `labels`.

If this is the case, please modify [`README.md`](https://github.com/yam-ai/bert-multilabel-classifier/blob/master/README.md) and [`example\data,db`](https://github.com/yam-ai/bert-multilabel-classifier/blob/master/example/data.db) accordingly. Thanks.

**Comment by michaelng-yam** [comment]
Add index to labels in dev branch

**Comment by tomlee** [comment]
@michaelng-yam Please also add index to [csv2sqlite.py](https://github.com/yam-ai/bert-multilabel-classifier/blob/master/example/csv2sqlite.py).

**Comment by tomlee** [comment]
Fixed on the `elaborate-example-setup` branch.
